platform :ios do
  desc "Match development certificates"
  lane :match_development do
    match(
      type: "development",
      readonly: true,
      app_identifier: [
        "com.percipia.connect",
        "com.percipia.connect.msgNotificationService",
        "com.percipia.connect.linphoneExtension"
      ]
    )
  end

  desc "Match appstore certificates"
  lane :match_appstore do
    match(
      type: "appstore",
      readonly: true,
      app_identifier: [
        "com.percipia.connect",
        "com.percipia.connect.msgNotificationService",
        "com.percipia.connect.linphoneExtension"
      ]
    )
  end

  desc "Build debug app"
  lane :build_debug do
    match_development
    
    build_app(
      scheme: "Linphone",
      configuration: "Debug",
      export_method: "development",
      export_team_id: ENV["TEAM_ID"],
      # xcargs: "-allowProvisioningUpdates DEVELOPMENT_TEAM=#{ENV['TEAM_ID']}",
      output_directory: "./build",
      output_name: "FrequencyConnect-Debug.ipa",
      export_options: {
        provisioningProfiles: {
          "com.percipia.connect" => "match Development com.percipia.connect",
          "com.percipia.connect.msgNotificationService" => "match Development com.percipia.connect.msgNotificationService",
          "com.percipia.connect.linphoneExtension" => "match Development com.percipia.connect.linphoneExtension"
        }
      }
    )
  end

  desc "Build production app"
  lane :build_prod do
    match_appstore
    
    build_app(
      scheme: "Linphone",
      configuration: "Release",
      export_method: "app-store",
      export_team_id: ENV["TEAM_ID"],
      # xcargs: "-allowProvisioningUpdates DEVELOPMENT_TEAM=#{ENV['TEAM_ID']}",
      output_directory: "./build",
      output_name: "FrequencyConnect-Production.ipa",
      export_options: {
        provisioningProfiles: {
          "com.percipia.connect" => "match AppStore com.percipia.connect",
          "com.percipia.connect.msgNotificationService" => "match AppStore com.percipia.connect.msgNotificationService",
          "com.percipia.connect.linphoneExtension" => "match AppStore com.percipia.connect.linphoneExtension"
        }
      }
    )
  end
end
