default_platform(:ios)

platform :ios do
  desc "Match development certificates"
  lane :match_development do
    match(
      type: "development",
      readonly: true
    )
  end

  desc "Match appstore certificates"
  lane :match_appstore do
    match(
      type: "appstore",
      readonly: true
    )
  end
end
